query SearchResults($genre: String!) {
  Movie(filter: { in_genre_single: { name: $genre } }, first: 60) {
    title
    year
    runtime
    poster
    imdbRating
    movieId
    in_genre {
      name
    }
  }
}
